name: GPRC
favicon: null
layout_spectrum: 0.45532731455750763
typography_spectrum: 0.4941989432554692
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.3060864012222737
  lightness: 0.6871472497005016
  saturation: 0.1064273314550519
  rhythmicContrast: 0.8477938082069159
purpose: []
