name: GPRC
favicon: null
layout_spectrum: 1
typography_spectrum: 0.85069
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#585858'
    - '#dfdfdf'
    - '#718ca1'
    - '#bdbdbd'
  brandStrength: 1
  lightness: 0.5625
  saturation: 0.5
  rhythmicContrast: 0
purpose: []
